export const CREATE_REPORT_SUCCESS = " CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_ERROR = "CREATE_REPORT_ERROR";
export const CREATE_REPORT_REQUEST = "CREATE_REPORT_REQUEST";

export const GET_FACULTY_SUCCESS = " GET_FACULTY_SUCCESS";
export const GET_FACULTY_ERROR = "GET_FACULTY_ERROR";
export const GET_FACULTY_REQUEST = "GET_FACULTY_REQUEST";

export const GET_COURSE_SUCCESS = " GET_COURSE_SUCCESS";
export const GET_COURSE_ERROR = "GET_COURSE_ERROR";
export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";

export const ADD_FACULTYS_SUCCESS = " ADD_FACULTYS_SUCCESS";
export const ADD_FACULTYS_ERROR = "ADD_FACULTYS_ERROR";
export const ADD_FACULTYS_REQUEST = "ADD_FACULTYS_REQUEST";

export const GET_FACULTYS_SUCCESS = " GET_FACULTYS_SUCCESS";
export const GET_FACULTYS_ERROR = "GET_FACULTYS_ERROR";
export const GET_FACULTYS_REQUEST = "GET_FACULTYS_REQUEST";

export const CREATE_BOOKING_SUCCESS = " CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";
export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";

export const CREATE_PAYMENT_SUCCESS = " CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";
export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";

export const ADD_FACULTYSS_SUCCESS = " ADD_FACULTYSS_SUCCESS";
export const ADD_FACULTYSS_ERROR = "ADD_FACULTYSS_ERROR";
export const ADD_FACULTYSS_REQUEST = "ADD_FACULTYSS_REQUEST";

export const GET_SINGLE_FACULTYSS_SUCCESS = " GET_SINGLE_FACULTYSS_SUCCESS";
export const GET_SINGLE_FACULTYSS_ERROR = "GET_SINGLE_FACULTYSS_ERROR";
export const GET_SINGLE_FACULTYSS_REQUEST = "GET_SINGLE_FACULTYSS_REQUEST";

export const EDIT_SINGLE_FACULTYSS_SUCCESS = " EDIT_SINGLE_FACULTYSS_SUCCESS";
export const EDIT_SINGLE_FACULTYSS_ERROR = "EDIT_SINGLE_FACULTYSS_ERROR";
export const EDIT_SINGLE_FACULTYSS_REQUEST = "EDIT_SINGLE_FACULTYSS_REQUEST";

export const DISCHARGE_PATIENT_SUCCESS = " DISCHARGE_PATIENT_SUCCESS";
export const DISCHARGE_PATIENT_ERROR = "DISCHARGE_PATIENT_ERROR";
export const DISCHARGE_PATIENT_REQUEST = "DISCHARGE_PATIENT_REQUEST";

export const GET_PATIENT_SUCCESS = " GET_PATIENT_SUCCESS";
export const GET_PATIENT_ERROR = "GET_PATIENT_ERROR";
export const GET_PATIENT_REQUEST = "GET_PATIENT_REQUEST";

export const GET_COURSE_DETAILS_SUCCESS =
  " GET_COURSE_DETAILS_SUCCESS";
export const GET_COURSE_DETAILS_ERROR = "GET_COURSE_DETAILS_ERROR";
export const GET_COURSE_DETAILS_REQUEST =
  "GET_COURSE_DETAILS_REQUEST";

export const GET_ALLDATA_SUCCESS = " GET_ALLDATA_SUCCESS";
export const GET_ALLDATA_REQUEST = "GET_ALLDATA_REQUEST";

export const DELETE_COURSE_SUCCESS = " DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";

export const GET_REPORTS_SUCCESS = " GET_REPORTS_SUCCESS";
export const GET_REPORTS_REQUEST = "GET_REPORTS_REQUEST";
