

export const LOGIN_FACULTY_SUCCESS = "LOGIN_FACULTY_SUCCESS";
export const LOGIN_FACULTY_ERROR = "LOGIN_FACULTY_ERROR";
export const LOGIN_FACULTY_REQUEST = "LOGIN_FACULTY_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_FACULTY_SUCCESS = " REGISTER_FACULTY_SUCCESS";
export const REGISTER_FACULTY_ERROR = "REGISTER_FACULTY_ERROR";
export const REGISTER_FACULTY_REQUEST = "REGISTER_FACULTY_REQUEST";


export const REGISTER_ADMIN_SUCCESS = " REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";


export const EDIT_FACULTY_SUCCESS = " EDIT_FACULTY_SUCCESS";
export const EDIT_FACULTY_ERROR = "EDIT_FACULTY_ERROR";
export const EDIT_FACULTY_REQUEST = "EDIT_FACULTY_REQUEST";

export const SEND_PASSWORD_SUCCESS = " SEND_PASSWORD_SUCCESS";
export const SEND_PASSWORD_ERROR = "SEND_PASSWORD_ERROR";
export const SEND_PASSWORD_REQUEST = "SEND_PASSWORD_REQUEST";

export const FORGET_PASSWORD_SUCCESS = " FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
